module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['../../apps', '../../packages'],
  testMatch: [
    '**/__tests__/**/*.spec.ts',
    '**/__tests__/**/*.test.ts',
    '**/*.spec.ts',
    '**/*.test.ts',
  ],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        tsconfig: {
          jsx: 'react-jsx',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          isolatedModules: true,
        },
      },
    ],
  },
  collectCoverageFrom: [
    'apps/**/*.ts',
    'packages/**/*.ts',
    '!apps/**/*.spec.ts',
    '!apps/**/*.test.ts',
    '!packages/**/*.spec.ts',
    '!packages/**/*.test.ts',
    '!apps/**/main.ts',
    '!apps/**/index.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/coverage/**',
    '!**/*.d.ts',
    '!**/*.config.ts',
    '!**/*.config.js',
  ],
  coverageDirectory: '<rootDir>/../../coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 75,
      lines: 75,
      statements: 75,
    },
    'apps/backend-gateway/': {
      branches: 80,
      functions: 85,
      lines: 80,
      statements: 80,
    },
    'packages/common-backend/': {
      branches: 85,
      functions: 90,
      lines: 85,
      statements: 85,
    },
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@tuheg/(.*)$': '<rootDir>/../../packages/$1/src',
    '^@/(.*)$': '<rootDir>/../../apps/frontend/src/$1',
    '^shared-types$': '<rootDir>/../../packages/shared-types/src',
    '^langfuse$': '<rootDir>/../../tests/mocks/langfuse.ts',
    '^langfuse/(.*)$': '<rootDir>/../../tests/mocks/langfuse.ts',
  },
  setupFilesAfterEnv: [
    '<rootDir>/../../packages/common-backend/test/setup.ts',
  ],
  testTimeout: 10000,
  maxWorkers: '50%',
  bail: 1,
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  clearMocks: true,
  restoreMocks: true,
  resetMocks: true,
  resetModules: true,
}
