# GitHub Labels Configuration
# This file defines the labels used in the repository

labels:
  # Priority labels
  - name: "priority: critical"
    color: "b60205"
    description: "Critical priority - needs immediate attention"

  - name: "priority: high"
    color: "d73a49"
    description: "High priority - should be addressed soon"

  - name: "priority: medium"
    color: "f9d0c4"
    description: "Medium priority - nice to have"

  - name: "priority: low"
    color: "bfdadc"
    description: "Low priority - future consideration"

  # Type labels
  - name: "bug"
    color: "d73a49"
    description: "Something isn't working"

  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"

  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"

  - name: "question"
    color: "d876e3"
    description: "Further information is requested"

  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"

  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  # AI-specific labels
  - name: "ai-bug"
    color: "ff6b6b"
    description: "Issues with AI agent behavior or responses"

  - name: "ai-feature"
    color: "4ecdc4"
    description: "New AI capabilities or agent improvements"

  - name: "agent-behavior"
    color: "45b7d1"
    description: "AI agent behavior and personality"

  - name: "narrative-quality"
    color: "f9ca24"
    description: "Storytelling and narrative generation quality"

  # Component labels
  - name: "frontend"
    color: "1abc9c"
    description: "Frontend/UI related issues"

  - name: "backend"
    color: "e67e22"
    description: "Backend/API related issues"

  - name: "creation-agent"
    color: "3498db"
    description: "World creation agent"

  - name: "logic-agent"
    color: "9b59b6"
    description: "Logic reasoning agent"

  - name: "narrative-agent"
    color: "e74c3c"
    description: "Story generation agent"

  - name: "backend-gateway"
    color: "95a5a6"
    description: "API gateway and coordination"

  # Status labels
  - name: "triage"
    color: "fbca04"
    description: "Needs triage"

  - name: "investigating"
    color: "fbca04"
    description: "Under investigation"

  - name: "confirmed"
    color: "fbca04"
    description: "Issue confirmed"

  - name: "in progress"
    color: "fbca04"
    description: "Work in progress"

  - name: "blocked"
    color: "fbca04"
    description: "Blocked by dependencies"

  - name: "ready for review"
    color: "fbca04"
    description: "Ready for code review"

  # Testing labels
  - name: "testing"
    color: "0e8a16"
    description: "Needs testing"

  - name: "needs tests"
    color: "b60205"
    description: "Missing test coverage"

  # Platform labels
  - name: "windows"
    color: "0366d6"
    description: "Windows specific"

  - name: "macos"
    color: "0366d6"
    description: "macOS specific"

  - name: "linux"
    color: "0366d6"
    description: "Linux specific"

  - name: "mobile"
    color: "0366d6"
    description: "Mobile platforms"

  - name: "web"
    color: "0366d6"
    description: "Web platform"

  # Special labels
  - name: "breaking change"
    color: "b60205"
    description: "Introduces breaking changes"

  - name: "security"
    color: "b60205"
    description: "Security related"

  - name: "performance"
    color: "fbca04"
    description: "Performance related"

  - name: "accessibility"
    color: "006b75"
    description: "Accessibility related"

  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"