# 自动回溯系统配置
# 基于监控指标自动触发回滚

apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-rollback-config
  namespace: production
data:
  # 回滚触发条件
  rollback_conditions: |
    {
      "error_rate_threshold": 0.05,
      "response_time_threshold": 5.0,
      "availability_threshold": 95.0,
      "consecutive_failures": 5,
      "evaluation_period": "5m",
      "cooldown_period": "30m"
    }

  # 回滚策略
  rollback_strategies: |
    {
      "rolling": {
        "type": "deployment_rollback",
        "command": "kubectl rollout undo deployment/tuheg-backend-gateway"
      },
      "blue_green": {
        "type": "traffic_switch",
        "command": "switch_to_previous_environment.sh"
      },
      "canary": {
        "type": "scale_down",
        "command": "kubectl scale deployment tuheg-backend-green --replicas=0"
      }
    }

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-rollback-monitor
  namespace: production
spec:
  schedule: "*/5 * * * *"  # 每5分钟检查一次
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: rollback-service-account
          containers:
          - name: rollback-monitor
            image: tuheg/monitoring-tools:latest
            command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -e

              echo "开始自动回溯监控检查..."

              # 获取当前部署状态
              DEPLOYMENT_STATUS=$(kubectl get deployment tuheg-backend-gateway -o jsonpath='{.status.conditions[?(@.type=="Available")].status}')

              if [ "$DEPLOYMENT_STATUS" != "True" ]; then
                echo "检测到部署不可用，准备回滚..."
                /scripts/trigger_rollback.sh deployment_unavailable
                exit 0
              fi

              # 检查错误率
              ERROR_RATE=$(curl -s http://prometheus:9090/api/v1/query?query='sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100' | jq -r '.data.result[0].value[1]')

              if (( $(echo "$ERROR_RATE > 5.0" | bc -l) )); then
                echo "检测到高错误率: ${ERROR_RATE}%，准备回滚..."
                /scripts/trigger_rollback.sh high_error_rate "$ERROR_RATE"
                exit 0
              fi

              # 检查响应时间
              RESPONSE_TIME=$(curl -s http://prometheus:9090/api/v1/query?query='histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))' | jq -r '.data.result[0].value[1]')

              if (( $(echo "$RESPONSE_TIME > 5.0" | bc -l) )); then
                echo "检测到慢响应时间: ${RESPONSE_TIME}s，准备回滚..."
                /scripts/trigger_rollback.sh slow_response_time "$RESPONSE_TIME"
                exit 0
              fi

              echo "所有指标正常，无需回滚"
          volumeMounts:
          - name: scripts
            mountPath: /scripts
          env:
          - name: PROMETHEUS_URL
            value: "http://prometheus:9090"
          - name: DEPLOYMENT_NAME
            value: "tuheg-backend-gateway"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
      - name: scripts
        configMap:
          name: rollback-scripts
          defaultMode: 0755
      restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rollback-scripts
  namespace: production
data:
  trigger_rollback.sh: |
    #!/bin/bash
    set -e

    REASON="$1"
    METRIC_VALUE="$2"

    echo "触发自动回滚 - 原因: $REASON, 指标值: $METRIC_VALUE"

    # 获取当前部署信息
    CURRENT_VERSION=$(kubectl get deployment tuheg-backend-gateway -o jsonpath='{.spec.template.spec.containers[0].image}' | cut -d: -f2)
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)

    # 创建回滚记录
    cat > /tmp/rollback_record.json << EOF
    {
      "timestamp": "$TIMESTAMP",
      "version": "$CURRENT_VERSION",
      "reason": "$REASON",
      "metric_value": "$METRIC_VALUE",
      "deployment_type": "$(kubectl get configmap deployment-config -o jsonpath='{.data.ACTIVE_COLOR}' 2>/dev/null || echo 'rolling')",
      "action": "rollback_triggered"
    }
    EOF

    # 发送告警通知
    curl -X POST -H 'Content-type: application/json' \
      --data @/tmp/rollback_record.json \
      "$ALERT_WEBHOOK_URL" || true

    # 执行回滚
    case "$DEPLOYMENT_TYPE" in
      "rolling")
        echo "执行滚动回滚..."
        kubectl rollout undo deployment/tuheg-backend-gateway
        kubectl rollout status deployment/tuheg-backend-gateway --timeout=300s
        ;;
      "blue-green")
        echo "执行蓝绿回滚..."
        ACTIVE_COLOR=$(kubectl get configmap deployment-config -o jsonpath='{.data.ACTIVE_COLOR}')
        if [ "$ACTIVE_COLOR" = "blue" ]; then
          INACTIVE_COLOR="green"
        else
          INACTIVE_COLOR="blue"
        fi

        # 切换回非活跃环境
        kubectl patch service tuheg-backend-gateway -p "{\"spec\":{\"selector\":{\"app\":\"backend-gateway\",\"color\":\"$INACTIVE_COLOR\"}}}"

        # 等待切换完成
        sleep 30

        # 更新配置
        kubectl patch configmap deployment-config --type merge -p "{\"data\":{\"ACTIVE_COLOR\":\"$INACTIVE_COLOR\"}}"
        ;;
      "canary")
        echo "执行金丝雀回滚..."
        kubectl delete ingress tuheg-canary-ingress --ignore-not-found=true
        kubectl scale deployment tuheg-backend-green --replicas=0
        ;;
    esac

    # 验证回滚成功
    sleep 60
    DEPLOYMENT_STATUS=$(kubectl get deployment tuheg-backend-gateway -o jsonpath='{.status.conditions[?(@.type=="Available")].status}')

    if [ "$DEPLOYMENT_STATUS" = "True" ]; then
      echo "回滚成功完成"

      # 发送成功通知
      cat > /tmp/rollback_success.json << EOF
      {
        "timestamp": "$(date +%Y%m%d_%H%M%S)",
        "version": "$CURRENT_VERSION",
        "reason": "$REASON",
        "action": "rollback_completed",
        "status": "success"
      }
      EOF

      curl -X POST -H 'Content-type: application/json' \
        --data @/tmp/rollback_success.json \
        "$ALERT_WEBHOOK_URL" || true
    else
      echo "回滚失败，人工干预可能需要"

      # 发送失败通知
      cat > /tmp/rollback_failed.json << EOF
      {
        "timestamp": "$(date +%Y%m%d_%H%M%S)",
        "version": "$CURRENT_VERSION",
        "reason": "$REASON",
        "action": "rollback_failed",
        "status": "failed"
      }
      EOF

      curl -X POST -H 'Content-type: application/json' \
        --data @/tmp/rollback_failed.json \
        "$ALERT_WEBHOOK_URL" || true
    fi

  health_check.sh: |
    #!/bin/bash
    # 健康检查脚本

    ENDPOINT="$1"
    TIMEOUT="${2:-10}"

    if curl -f -s --max-time "$TIMEOUT" "$ENDPOINT" >/dev/null 2>&1; then
      echo "healthy"
      exit 0
    else
      echo "unhealthy"
      exit 1
    fi

  performance_check.sh: |
    #!/bin/bash
    # 性能检查脚本

    ENDPOINT="$1"
    SAMPLES="${2:-10}"

    total_time=0
    success_count=0

    for i in $(seq 1 "$SAMPLES"); do
      start_time=$(date +%s%N)
      if curl -f -s "$ENDPOINT" >/dev/null 2>&1; then
        end_time=$(date +%s%N)
        response_time=$(( (end_time - start_time) / 1000000 ))
        total_time=$((total_time + response_time))
        ((success_count++))
      fi
      sleep 0.1
    done

    if [ "$success_count" -gt 0 ]; then
      avg_response_time=$((total_time / success_count))
      success_rate=$((success_count * 100 / SAMPLES))

      echo "{\"avg_response_time_ms\": $avg_response_time, \"success_rate_percent\": $success_rate}"
    else
      echo "{\"error\": \"no_successful_requests\"}"
    fi
