name: 🤖 AI Dialogue Bug
description: Report issues with AI agent behavior or dialogue generation
title: "[AI Bug]: "
labels: ["ai-bug", "agent-behavior", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an AI-related issue!

        ## 🤖 AI Dialogue Bug Report

  - type: textarea
    id: description
    attributes:
      label: Describe the AI issue
      description: What went wrong with the AI behavior?
      placeholder: |
        Describe what the AI did incorrectly:
        - Unexpected dialogue response
        - Logical inconsistency
        - Character behavior issues
        - World state errors
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Which AI Agent?
      description: Which agent exhibited the problematic behavior?
      options:
        - Creation Agent (World building)
        - Logic Agent (Rule validation)
        - Narrative Agent (Story generation)
        - Backend Gateway (System coordination)
        - Multiple agents
        - Not sure
    validations:
      required: true

  - type: textarea
    id: input
    attributes:
      label: User Input
      description: What did you input to trigger this behavior?
      placeholder: "The exact text/command you entered..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected AI Response
      description: What should the AI have done?
      placeholder: "Describe the correct behavior..."

  - type: textarea
    id: actual
    attributes:
      label: Actual AI Response
      description: What did the AI actually do?
      placeholder: "Copy the AI's response here..."

  - type: textarea
    id: context
    attributes:
      label: Game Context
      description: Provide context about the game state when this occurred.
      placeholder: |
        - Game world description
        - Character information
        - Current scene/plot
        - Previous interactions

  - type: dropdown
    id: severity
    attributes:
      label: Impact on Experience
      description: How much does this affect the user experience?
      options:
        - Critical (Makes game unplayable)
        - High (Major story/logic breaks)
        - Medium (Minor inconsistencies)
        - Low (Cosmetic issues)
    validations:
      required: true

  - type: input
    id: session
    attributes:
      label: Session/Game ID
      description: If you have a session or game ID, please provide it.
      placeholder: "session-12345 or game-abc123"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other relevant information.
      placeholder: |
        - Screenshots of the conversation
        - Multiple examples of the issue
        - When did this start happening?
        - Any patterns you've noticed

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: I have tested this with multiple inputs
          required: false
        - label: I have provided the exact input that caused the issue
          required: true
        - label: I have included the AI's actual response
          required: true
        - label: I have searched for similar AI behavior issues
          required: true