name: 🚀 AI Feature Request
description: Suggest new AI capabilities or agent improvements
title: "[AI Feature]: "
labels: ["ai-feature", "enhancement", "agent-improvement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an AI feature!

        ## 🚀 AI Feature Request

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: What new AI capability would you like to see?
      placeholder: "E.g., Voice synthesis for characters, Image generation, Multi-language support..."
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Target Agent
      description: Which AI agent should this feature enhance?
      options:
        - Creation Agent (World building)
        - Logic Agent (Rule validation)
        - Narrative Agent (Story generation)
        - Backend Gateway (System coordination)
        - New Agent (Propose a new agent type)
        - Cross-agent feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Current Limitation
      description: What can't the AI do now that this feature would enable?
      placeholder: |
        Describe what's currently missing:
        - Creative limitations
        - Technical constraints
        - User experience gaps
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed AI Enhancement
      description: How should this feature work from a user perspective?
      placeholder: |
        Describe the user experience:
        - How users would interact with this feature
        - Example use cases
        - Expected outcomes

  - type: textarea
    id: technical
    attributes:
      label: Technical Implementation
      description: Any technical details or requirements you know about?
      placeholder: |
        Technical considerations:
        - AI model requirements
        - API integrations needed
        - Data processing requirements
        - Performance implications

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this would be?
      options:
        - Low (Model fine-tuning, prompt engineering)
        - Medium (New AI integrations, data pipelines)
        - High (New agent architecture, major AI research)
        - Very High (Fundamental AI paradigm shift)
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Scenarios
      description: Provide specific examples of how this feature would be used.
      placeholder: |
        Example 1: [Scenario description]
        Example 2: [Another scenario]
        Example 3: [Edge case]

  - type: dropdown
    id: priority
    attributes:
      label: Business Impact
      description: How important is this for user adoption?
      options:
        - Nice to have (Quality of life improvement)
        - Important (Competitive advantage)
        - Critical (Differentiator vs competitors)
        - Game-changer (Opens new use cases)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Have you considered other ways to achieve this?
      placeholder: |
        Alternative solutions:
        - Third-party integrations
        - Manual user workflows
        - Simplified implementations

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information or research you've done.
      placeholder: |
        - Research papers or articles
        - Similar features in other AI systems
        - Technical feasibility analysis
        - Market research

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: I have searched for similar AI feature requests
          required: true
        - label: This feature would significantly improve AI capabilities
          required: false
        - label: I have considered the technical feasibility
          required: false
        - label: I am willing to contribute to the implementation
          required: false