name: 🐛 Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        ## 🐛 Bug Report

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
      placeholder: A clear and concise description of what you expected to happen.

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: A clear and concise description of what actually happened.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Some functionality broken)
        - Low (Minor issue)
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment.
        Examples: Browser version, OS, Node.js version, etc.
      placeholder: "Chrome 91.0, Windows 10, Node.js 18.0.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        - Screenshots
        - Console logs
        - Network requests
        - Related issues

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have provided a clear description of the bug
          required: true
        - label: I have provided steps to reproduce the bug
          required: true
        - label: I have included environment details
          required: false
