name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

        ## ✨ Feature Request

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief description of the feature you'd like to see.
      placeholder: What's the feature about?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        Describe the problem this feature would solve:
        - Current limitations
        - User pain points
        - Missing functionality
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your proposed solution:
        - How it should work
        - User experience
        - Technical implementation (if you have ideas)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: |
        Alternative approaches you've considered:
        - Workarounds
        - Different implementation methods
        - Related features that could be extended

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical/blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Small UI/UX changes)
        - Medium (New components/pages)
        - Complex (Major new features)
        - Very Complex (Architecture changes)
        - Unknown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else you'd like to add?
      placeholder: |
        - Screenshots/mockups
        - Related issues
        - Links to similar features in other products
        - Technical specifications

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply.
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature would benefit other users
          required: false
        - label: I am willing to contribute to the implementation
          required: false
